"""rename department

Revision ID: 72c488713707
Revises: 85d5cf8cb4bc
Create Date: 2024-09-03 21:09:10.258011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c488713707'
down_revision = '85d5cf8cb4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 op.rename_table('departments', 'department')
    # ### end Alembic commands ###
